# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfc0d4798b93838bac27a9bce6552a5e7caa235f48af62abf016988bfa019cafc85baa4724c372df16a2b53b09db9b82eb227ea20c0299d0226c8b3057b6e9ba

test:
  secret_key_base: 2600fdb3ab9e8d99068f3b0c3b0d9ac1cce303763902060f47a09ff4bdd7228a2db53a7af2e09cb4c5e51489a417357fef112bf9b2407bc96e8ee5d7098a2ab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
